app/src/main/java/com/sq/thed_ck_licker/Game.kt
app/src/main/java/com/sq/thed_ck_licker/MainActivity.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/ComponentManager.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/EntityManager.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/TheGameHandler.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/CardComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/MiscComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/CardDisplaySystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/CardEffectSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/DescriptionSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ui/components/buttons/PullCardButton.kt
app/src/main/java/com/sq/thed_ck_licker/ui/components/views/CardDeck.kt

19-kortin-aktivointi_hylkääminen-2

---

app/src/main/java/com/sq/thed_ck_licker/player/Player.kt

player hp and max hp are drawn inside the bar.

refactored the hp bar 

---

app/build.gradle.kts
app/src/main/java/com/sq/thed_ck_licker/Game.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/EntityManager.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/CardComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/PlayerComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/ActivationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/PullCardSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardDisplaySystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardsSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/MerchantSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/PlayerSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/EffectStackSystems.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/OnDeathSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/onDiscardSystem.kt
app/src/test/java/com/sq/thed_ck_licker/ecs/ComponentManagerTest.kt
app/src/test/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/PlayerSystemTest.kt
app/src/test/java/com/sq/thed_ck_licker/helpers/MyRandomTest.kt

Discard deck should be working now.
It required small other changes too but they should be working too.

2 discard pakka

---

app/src/main/java/com/sq/thed_ck_licker/ecs/components/MiscComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardDisplaySystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/MerchantSystem.kt

63 shop reroll

---

app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystem.kt

Default prevention of overheal

Prevented overheal

---

app/src/main/java/com/sq/thed_ck_licker/Game.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/CardComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/MiscComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/PlayerComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/managers/ComponentManager.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/CardPullingSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/DescriptionSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardsSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/MerchantSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/PlayerSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/EffectStackSystems.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/OnDeathSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/onDiscardSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/CardView.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/MerchantHandView.kt
app/src/main/java/com/sq/thed_ck_licker/viewModels/MerchantViewModel.kt

Made component params private.
Made functions for modifying the component values.
This way we can make changes to only one place if, for example, we need to change how healing works.
Also fixed a bug with the merchant:
If player bought a card that could die. The next shop open would crash the game.
This was due not reseting the merchant hand after player chose a card.

75 make component params private

---

app/src/main/java/com/sq/thed_ck_licker/Game.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/MiscComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/managers/EventManager.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardsSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/MerchantSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/PlayerSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/HoleView.kt
app/src/main/java/com/sq/thed_ck_licker/viewModels/GameViewModel.kt

issue: #60 
Player can now dig a hole with a shovel
Shovel can be bought from merchant
Using another shovel closes the hole
If player runs out of cards they die 💀

60 dig a hole

---

app/src/main/java/com/sq/thed_ck_licker/Game.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/CardComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/MiscComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/states/MerchantState.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/PitSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/WorldCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardBuilderSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/MerchantSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/DescriptionSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/CardView.kt
app/src/main/java/com/sq/thed_ck_licker/helpers/GameSystemModule.kt
app/src/main/java/com/sq/thed_ck_licker/helpers/HelperSystemModule.kt
app/src/main/java/com/sq/thed_ck_licker/helpers/PitSystemModule.kt
app/src/main/java/com/sq/thed_ck_licker/viewModels/GameViewModel.kt
app/src/main/java/com/sq/thed_ck_licker/viewModels/MerchantViewModel.kt

Created an entity memory component.
Component is now only added to merchant and has only affinity value
Buying cards increase affinity by 10
Trying to throw merchant into the pit and failing decreases affinity by -500
If merchant is mad then everything is more expensive and tehre is extra text in the ui.

made memory component

---

app/build.gradle.kts
app/src/main/java/com/sq/thed_ck_licker/Game.kt
app/src/main/java/com/sq/thed_ck_licker/MainActivity.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/managers/EntityManager.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/DeathScreen.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/GameNavigation.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/HighScoreScreen.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/MainMenuScreen.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/SettingsScreen.kt
app/src/main/java/com/sq/thed_ck_licker/helpers/navigation/GameRoutes.kt
app/src/main/java/com/sq/thed_ck_licker/viewModels/GameViewModel.kt
gradle/libs.versions.toml

Created main menu and base for the navigation in the game.
Returning to main menu after dying does not work at the moment, since we need some refactoring regarding other navigation for it. I believe it is best to be done on its own issue, so that this PR wont become too big.

Created main menu for the game

---

app/src/main/java/com/sq/thed_ck_licker/ecs/components/MiscComponents.kt

Simplified the health component by consolidating the `heal` and `damage` functions into a single `add` function. This makes the code more concise and easier to maintain.
The `add` function now handles both healing and damaging, with an optional `targetId` parameter for damage events. It also includes the death check logic, which was previously in the `damage` function.
The `heal` and `damage` functions are now simple wrappers around the `add` function.

Refactored health component

---

app/src/main/java/com/sq/thed_ck_licker/Game.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/MiscComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/SettingsScreen.kt

A checkbox for "hurryness" has been added to the settings screen. When checked, the player will take 1 damage every second.

Proof of concept: Periodic damage effect

---

app/build.gradle.kts
app/src/main/java/com/sq/thed_ck_licker/ecs/components/CardComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/MultiplierComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/misc/HealthComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/misc/MiscComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/misc/ScoreComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/managers/ComponentManager.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardBuilderSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardsSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/MerchantSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/PlayerSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/DescriptionSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/MultiplierSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/OnDeathSystem.kt
app/src/main/java/com/sq/thed_ck_licker/helpers/CardSystemModule.kt
app/src/main/java/com/sq/thed_ck_licker/helpers/HelperSystemModule.kt
app/src/test/java/com/sq/thed_ck_licker/ecs/components/MultiplierComponentTest.kt
app/src/test/java/com/sq/thed_ck_licker/ecs/managers/ComponentManagerTest.kt
app/src/test/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/MultiplierSystemKtTest.kt

Hurray it may finally work...
Also now that this is (probably...) working, i think we can finally make some small time demo quality thing to get the minimum playable version going.
Fancy feeling, thou there is still lots of things to do but now we can start to feelistellä how the game actually would feel like.
I am not sure if the current multiplier is actually temp one.
It might as well be permanent.
Also also not sure if this caused it but I managed to die with full hp.
That should not be possible, if that happened cuz I ran out of cards, it should have done massive damage to me.
Maybe there should be mechanic arond it actually.
If the player deck is empty Reaper card(?) Deaths door(?) is added that deals ever growing damage to player.
Then some clever player can find a some bizarre way …

46 the multiplier system yet again

---

app/src/main/java/com/sq/thed_ck_licker/ecs/components/EffectComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/PlayerSystem.kt

First version of some sort of corruption system.
I am not entirely sure it is working as intented but I am pretty sure.

Corruption at its finest

---

app/src/main/java/com/sq/thed_ck_licker/MainActivity.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/managers/EventManager.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/WorldCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/GameNavigation.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/DeathScreen.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/GameScreen.kt
app/src/main/java/com/sq/thed_ck_licker/helpers/navigation/GameNavigator.kt
app/src/main/java/com/sq/thed_ck_licker/viewModels/GameViewModel.kt

Death screen is now its own screen. 
Also fixed some issues regarding it:
Leave game button now works after death.
Death events are no longer lingering after game restart

Death screen navigation

---

app/src/test/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/PlayerSystemTest.kt
build.gradle.kts

Commented PlayerTest out and added the dependency needed for instrumented testing.

Now test should pass again.

---

app/src/main/java/com/sq/thed_ck_licker/ecs/managers/EventManager.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/PitSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/MerchantSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/CardRow.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/MerchantHandView.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/GameNavigation.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/GameScreen.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/MerchantScreen.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/PitScreen.kt
app/src/main/java/com/sq/thed_ck_licker/helpers/PitSystemModule.kt
app/src/main/java/com/sq/thed_ck_licker/helpers/navigation/GameNavigator.kt
app/src/main/java/com/sq/thed_ck_licker/helpers/navigation/GameRoutes.kt
app/src/main/java/com/sq/thed_ck_licker/ui/theme/Theme.kt
app/src/main/java/com/sq/thed_ck_licker/viewModels/GameViewModel.kt
app/src/main/java/com/sq/thed_ck_licker/viewModels/MerchantViewModel.kt
app/src/main/java/com/sq/thed_ck_licker/viewModels/PitViewModel.kt

Pit has own screen now and works similiarly to merchant

99 pit screen

---

app/src/main/java/com/sq/thed_ck_licker/ecs/components/ActivationComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/CardComponents.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/DiscardDeckComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/DrawDeckComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/EffectComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/EffectStackComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/HistoryComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/TagsComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/managers/ComponentManager.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardBuilderSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardsSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/MerchantSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/PlayerSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/MultiplierSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/OnDeathSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/GameScreen.kt
app/src/main/java/com/sq/thed_ck_licker/helpers/DescribedEffect.kt
app/src/main/java/com/sq/thed_ck_licker/player/Player.kt
app/src/test/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystemTest.kt
app/src/test/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardsSystemTest.kt
app/src/test/java/com/sq/thed_ck_licker/helpers/DescribedEffectTest.kt

Main thing is the added missing target id to the description of described effect.

Refactor: Enhance EffectComponent and DescribedEffect

---

app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/CardDeckSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/CardRow.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/CardView.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/MerchantHandView.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/PlayerHandView.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/PullCardButton.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/GameScreen.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/PitScreen.kt

Also moved the card count to show on deck, since I could not get it to look nice on cards in Zooming.

110 Cards can be zoomed on and added card health to cards top corner

---

app/src/main/java/com/sq/thed_ck_licker/ecs/components/ActivationCounterComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/HistoryComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/misc/EntityMemoryComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/misc/LatestCardComponent.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/misc/PriceComponent.kt

After these open pr's have been closed, we should have only components that implement the component marker interface.

Refactor: Implement Component interface for several components

---

.idea/codeStyles/Project.xml
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/conditionals/DeckTarget.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/conditionals/FlipTargets.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/conditionals/OnNumberedActivations.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/conditionals/OnThresholdActivations.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/conditionals/SelfTarget.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/damageEffects/ResetTakeRisingDamage.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/damageEffects/TakeDamage.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/healthEffects/GainMaxHealth.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/healthEffects/HealOnUnderThreshold.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/healthEffects/MultiplyMaxHp.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/miscEffects/AddEffectsToTrigger.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/scoreEffects/GainScore.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/components/effectthing/scoreEffects/TakeRisingScore.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/managers/locationmanagers/ForestManager.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/WorldCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/CardCreationSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/cardSystems/TriggerEffectHandler.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/characterSystems/PlayerSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/helperSystems/DeathSystem.kt
app/src/main/java/com/sq/thed_ck_licker/ecs/systems/viewSystems/navigationViews/screens/GameScreen.kt

Added some new conditionals.
This also contains the first-location-part2, this is not actully so so big.

Atomic effects
